'''
This file contains all the constants
'''
import sys
sys.path.append('../')

STR_UNDEFINED = 'Undefined'

'''
Below fields are related to Google Drive API
'''
CLIENTSECRET_LOCATION = '/home/leelab/PycharmProjects/moleculardating/application/auth/client_secret.json'
#CLIENTSECRET_LOCATION = '/Users/shivankurkapoor/GitHub/moleculardating/application/auth/client_secret.json'
REDIRECT_URI = 'postmessage'
SCOPES = [
    'https://www.googleapis.com/auth/drive.file'
    # Add other requested scopes.
]
ORIGIN = 'http://localhost:5000'


'''
This is the Application secret key of our application.
This is not generated by Google or any third-party API
'''
APP_SECRET_KEY = 'MoleDat:AQWER-WDSEE-DDEWE-WECEG8'


'''
Renew Token URI
'''
RENEW_TOKEN_URL = 'accounts.google.com'
RENEW_TOKEN_PATH = '/o/oauth2/token'
RENEW_TOKEN_PARAMS = 'client_id={client_id}&client_secret={client_secret}&refresh_token={refresh_token}&grant_type={grant_type}'


'''
GOOGLE DRIVE FILE HANDLING
'''
DOWNLOAD_FILE_URL = 'googleapis.com/drive/v2/files/{fileId}?alt=media'
DOWNLOAD_FILE_PATH = '/home/leelab/PycharmProjects/moleculardating/downloadedfiles/{request_id}'
#DOWNLOAD_FILE_PATH = '/Users/shivankurkapoor/GitHub/moleculardating/downloadedfiles/{request_id}'
MIME_TYPE = 'application/octet-stream'

DESCRIPTION = ''

'''
MISC
'''
INT_LEN_REQUEST_ID = 20
INT_TTL_GEN_ID = 10


'''
Error Codes for various purpose
'''
INT_ERROR_GENERAL = -1000
INT_ERROR_NOTEXIST = -3000
INT_ERROR_FOUND = -3001
INT_ERROR_PASSEDEXPTIME = -2000
INT_ERROR_FORMAT = -4000
INT_ERROR_TIMEOUT = -4008
INT_ERROR_MAXATTEMPTREACHED = -40080
INT_FAILURE = -1001
INT_FAILURE_AUTH = -1002
INT_FAILURE_RENEW = -1003
INT_ILLEGAL_HTTPMETHOD = -4001
INT_NOTEXISTS = 3000
INT_FOUND = 3001
INT_LOGGEDOUT = 1009
INT_OK = 0
INT_CREATED = 2001
INT_FAILURE_DOWNLOAD = -5001
INT_FAILURE_UPLOAD = -5002
INT_DOWNLOADED = 5001
INT_UPLOADED = 5002

'''
bioinformatics pipeline related constants
'''
INPUT_FILE_PATH = '../requests'

'''
taxonomy annotation program related constants
'''
USERFILE = None		#the user file for which family annotations need to be found out
REFFILE = 'current_Bacteria_aligned.fa'		#the reference file which will be used to find the taxonomy annotation
#REFFILE = '/Users/zifanwang/Downloads/RDPDataset/current_Bacteria_aligned.fa'
OUTPUTDIRECTORY = None	#the directory where the output file needs to be saved
#SUBINDEXEDREFFILEDIRECTORY = '../subindexedRefFiles/'		#the reference file which will be used to find out the family annotations
#SUBINDEXEDREFFILEDIRECTORY = '/Users/zifanwang/Downloads/RDPDataset/SubIndexedRefFiles10000/'
SUBINDEXEDREFFILEDIRECTORY = '../SubIndexedRefFiles10000/'
START = 0			#the base number where the region of interest starts in the reference sequence
END = 0				#the base number where the region of interest ends in the reference sequence
GAPREMOVEDUSERFILE = None	#the gap removed user file
TAXONOMY_OUTPUT_DIR = 'TaxonomyOutput/'
GRAPH_FILE_NAME = 'abundance_info.png'
ZIP_OUTPUT_FILE_NAME = 'taxonomy_output.zip'


'''
Request Form Types
'''
SINGLE = 'single'
SANGER_SEQUNCE_DATA = 'ss' #Sanger Sequence Data
MULTIPLE = 'multiple'
NEXT_GEN_DATA = 'ngs' #Next Generation Sequence Data
