#Configuration for prediction interval parameters
predictioninterval:
  fit_slope: '494.80'
  fit_intercept: '0.0'
  lower_slope: '430.2475'
  lower_intercept: '-74.0985'
  upper_slope: '558.7468'
  upper_intercept: '74.5164'

#Configuration for main.py
mainconfig:
  type: 'chronic'
  threshold_gsi: '0.2'
  threshold_clustering: '7.' #beta threshold
  threshold_diversity: '0.779'
  effective_diversity_th: '0.779'
  threshold_numseq: '4'
  gaps_ignore: 'True'
  gsi_num: 'GSI4'

#Configurations for filenames
filenames:
  diversity_file: 'diversity.npy'
  hd_file: 'hd.npy'
  gsi_file: 'gsi.txt'
  report_file: 'report.csv'
  final_report: 'final.csv'
  plot: 'plot'
  pred_interval_file: 'predictioninterval.csv'
  pred_interval_txt_file: 'predictioninterval.txt'

#Template Path
html:
  html_template: 'template.html'
  image_width: '550'
  image_height: '350'
